## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Maurício Luiz Sobrinho**<br>

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [11]:
import numpy as np

### Exercício 1)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [2]:

# Criar um array unidimensional com 30 números inteiros aleatórios entre 0 e 20
array_unidimensional = np.random.randint(0, 21, 30)

# Reformatar o array para uma matriz 5x6
matriz_A = array_unidimensional.reshape(5, 6)

print("Array unidimensional:")
print(array_unidimensional)
print("\nMatriz A:")
print(matriz_A)


Array unidimensional:
[15 19 10 11 13 13  1  8  4 17 14  0  0  7 19 16  7  3  0  1 17  9  4  8
  8 20 12  5  3  4]

Matriz A:
[[15 19 10 11 13 13]
 [ 1  8  4 17 14  0]
 [ 0  7 19 16  7  3]
 [ 0  1 17  9  4  8]
 [ 8 20 12  5  3  4]]


### Exercício 2)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [12]:

# Criar a matriz A
matriz_A = np.array([[ 4,  7,  2, 12, 15,  0],
                     [ 6, 17, 11,  1,  5, 18],
                     [ 7, 11, 14,  9,  3,  6],
                     [ 2, 19,  4,  8,  6,  8],
                     [ 7,  1,  9, 16, 12, 10]])

# Criar views da matriz A conforme as especificações
view1 = matriz_A[[0, 1, 3]]  # Linhas 0, 1 e 3
view2 = matriz_A[[1, 2]][:, [0, 2, 4]]  # Linhas 1 e 2, Colunas 0, 2 e 4
view3 = matriz_A[[1, 3]][:, [1, 3]]  # Linhas 1 e 3, Colunas 1 e 3

# Imprimir as views criadas
print("View 1:")
print(view1)
print("\nView 2:")
print(view2)
print("\nView 3:")
print(view3)


View 1:
[[ 4  7  2 12 15  0]
 [ 6 17 11  1  5 18]
 [ 2 19  4  8  6  8]]

View 2:
[[ 6 11  5]
 [ 7 14  3]]

View 3:
[[17  1]
 [19  8]]


### Exercício 3)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [13]:

# Criar o array bidimensional A
A = np.random.randint(0, 21, size=(5, 6))

# Fazer uma cópia do array A
Ac = A.copy()

# Substituir elementos maiores que 10 por -1 no array A
A[A > 10] = -1

# Substituir elementos maiores que 7 e menores que 15 por -1 no array Ac
Ac[(Ac > 7) & (Ac < 15)] = -1

# Imprimir os arrays modificados
print("Array A:")
print(A)
print("\nArray Ac:")
print(Ac)



Array A:
[[-1  2 -1 -1 -1  0]
 [-1 -1 -1  3  5 -1]
 [-1 -1 -1 -1 10  0]
 [ 5 -1  8  1 -1 -1]
 [ 7  4  8 -1  7 -1]]

Array Ac:
[[15  2 -1 17 16  0]
 [20 20 -1  3  5 18]
 [-1 20 -1 18 -1  0]
 [ 5 20 -1  1 16 -1]
 [ 7  4 -1 19  7 17]]


### Exercício 4)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [14]:

# Criar o array bidimensional A
A = np.arange(1, 201).reshape(20, 10)

# Criar a view A_lpares contendo linhas de A com índice par
A_lpares = A[::2]

# Criar a view A_lpares_cimpares contendo linhas de A com índice par e colunas com índice ímpar
A_lpares_cimpares = A[::2, 1::2]

# Imprimir as views
print("View A_lpares:")
print(A_lpares)
print("\nView A_lpares_cimpares:")
print(A_lpares_cimpares)


View A_lpares:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 81  82  83  84  85  86  87  88  89  90]
 [101 102 103 104 105 106 107 108 109 110]
 [121 122 123 124 125 126 127 128 129 130]
 [141 142 143 144 145 146 147 148 149 150]
 [161 162 163 164 165 166 167 168 169 170]
 [181 182 183 184 185 186 187 188 189 190]]

View A_lpares_cimpares:
[[  2   4   6   8  10]
 [ 22  24  26  28  30]
 [ 42  44  46  48  50]
 [ 62  64  66  68  70]
 [ 82  84  86  88  90]
 [102 104 106 108 110]
 [122 124 126 128 130]
 [142 144 146 148 150]
 [162 164 166 168 170]
 [182 184 186 188 190]]


### Exercício 5)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [15]:

# Criar o array bidimensional A com números inteiros de 1 até 200
A = np.arange(1, 201).reshape(20, 10)

# Criar a máscara booleana para elementos com pelo menos um índice par
mask = (A % 2 == 0)

# Substituir elementos por -1 de acordo com a máscara
A[mask] = -1

# Imprimir o array modificado
print("Array A modificado:")
print(A)


Array A modificado:
[[  1  -1   3  -1   5  -1   7  -1   9  -1]
 [ 11  -1  13  -1  15  -1  17  -1  19  -1]
 [ 21  -1  23  -1  25  -1  27  -1  29  -1]
 [ 31  -1  33  -1  35  -1  37  -1  39  -1]
 [ 41  -1  43  -1  45  -1  47  -1  49  -1]
 [ 51  -1  53  -1  55  -1  57  -1  59  -1]
 [ 61  -1  63  -1  65  -1  67  -1  69  -1]
 [ 71  -1  73  -1  75  -1  77  -1  79  -1]
 [ 81  -1  83  -1  85  -1  87  -1  89  -1]
 [ 91  -1  93  -1  95  -1  97  -1  99  -1]
 [101  -1 103  -1 105  -1 107  -1 109  -1]
 [111  -1 113  -1 115  -1 117  -1 119  -1]
 [121  -1 123  -1 125  -1 127  -1 129  -1]
 [131  -1 133  -1 135  -1 137  -1 139  -1]
 [141  -1 143  -1 145  -1 147  -1 149  -1]
 [151  -1 153  -1 155  -1 157  -1 159  -1]
 [161  -1 163  -1 165  -1 167  -1 169  -1]
 [171  -1 173  -1 175  -1 177  -1 179  -1]
 [181  -1 183  -1 185  -1 187  -1 189  -1]
 [191  -1 193  -1 195  -1 197  -1 199  -1]]


### Exercício 6)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [16]:

# Gerar o array X com distribuição uniforme no intervalo entre 0 e 1
X = np.random.uniform(0, 1, 20)

# Converter o array em uma lista e ordenar
X_sorted = sorted(X)

# Encontrar os três menores valores
tres_menores = X_sorted[:3]

# Imprimir os três menores valores
print("Os três menores valores do array X:")
print(tres_menores)


Os três menores valores do array X:
[0.05889728554058771, 0.06811038357780741, 0.08547833447634756]


### Exercício 7)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [17]:
def troca_colunas(array, col1, col2):
    array[:, [col1, col2]] = array[:, [col2, col1]]
    return array

X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X, 1, 3)
print(X)


[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 8)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [18]:
def zerar_abaixo_diagonal(matriz):
    linhas, colunas = matriz.shape
    for i in range(linhas):
        for j in range(i + 1, colunas):
            matriz[i, j] = 0
    return matriz

matriz = np.array([[2, 8, 3, 4, 8],
                   [4, 8, 7, 7, 3],
                   [8, 2, 3, 1, 4],
                   [8, 6, 3, 8, 1],
                   [6, 4, 4, 6, 1]])

matriz_zerada = zerar_abaixo_diagonal(matriz)
print(matriz_zerada)

# Este código define uma função zerar_abaixo_diagonal que 
# percorre a matriz e zera todos os elementos abaixo da diagonal principal.

[[2 0 0 0 0]
 [4 8 0 0 0]
 [8 2 3 0 0]
 [8 6 3 8 0]
 [6 4 4 6 1]]
